### ISSUE TITLE
unknown commands do not show a useful error

### ISSUE THREAD

**Issue by catdad** [catdad/json-cli-toolkit#14]
`echo {} | json fudge`

```
C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\toolkit.js:21
    return commands[command](data, opts);
                            ^

TypeError: commands[command] is not a function
    at runCommand (C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\toolkit.js:21:29)
    at run (C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\toolkit.js:42:16)
    at C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\toolkit.js:77:23
    at C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\node_modules\node-stream\lib\waitJson.js:19:9
    at C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\node_modules\node-stream\lib\wait.js:13:9
    at DestroyableTransform.end (C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\node_modules\node-stream\lib\waitObj.js:12:9)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at endReadableNT (C:\Users\kvatev\Documents\GitHub\json-cli-toolkit\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:865:12)
    at nextTickCallbackWith2Args (node.js:441:9)
```

I can do better than this error.

- [x] figure out how to handle these errors
- [x] print better error in the CLI

**Comment by catdad** [comment]
Published in 0.6.2.
